---
title: "Assessment 1.1"
author: "Syeda Faiza Hussain - s4647284"
date: "22/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!--2. Create Heading -->

# RMarkdown ***editing***

<!-- 3. Sentences about RMarkdown -->

R Markdown is a file format for making dynamic documents with R. An R Markdown document is written in markdown and contains chunks of embedded R code. R Markdown files are designed to be used with the rmarkdown package.

<!-- 4. Give bold and italics to editing in Heading (***editing***), I use three times *** to show editing word as both bold and italics -->

<!-- 5. Include an in-text link -->

[links](https://rmarkdown.rstudio.com/lesson-8.html)

<!-- 6. Insert an R chunk and create a variable with the dataset. We do not need to use readr::read_csv to load data as that's the tidyverse package and we have already that one in library(tidyverse). Read_csv performs the same function and easy to code.-->

```{r}
#install.packages
#install.packages("tidyverse")
#install.packages("skimr")

library(tidyverse)

fastfood <-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")

```
<!-- 7.	Display the first 10 rows of the dataset with the first 5 variables. 
For this, I have used 1:6 instead of 1:5 as the first column shows numbering and is not variable. For rows, I have added 10 in the fastfood column to make it easy to understand.-->

```{r}

knitr::kable(head(fastfood[, 1:6], 10), "pipe")

```
<!-- 8.	Display the observations that has more than 1000 calories.
For this, I have use the subset function of filter to include above 1000 calories and select the observations which are mainly linked to the variables such as restaurant and item. -->

```{r}

fastfood %>%
  subset(calories>1000, select=c(restaurant, item, calories))
  
```
<!-- 9.	Save observations with more than 40 in total_fat and more than 80 in total_carb in a new variable (dataset) called dont_eat_this. 
For this, I have use the mutate function to create a new variable dont_eat_this.-->

```{r}

fastfood %>%
  select(total_fat, total_carb) %>%
  filter(total_fat>"40", total_carb>"80")

dont_eat_this<- fastfood %>%
   mutate(dont_eat_this=as.numeric(total_fat>40 & total_carb>80))

#As this is a logical data, so the result would be either a boolean (TRUE or FALSE) or a numeric one by using as.numeric. The parse_number cannot be used here as it is showing error for two values. Now, with as.numeric, it is showing data as numeric in new variable dont_eat_this.

```

<!--10.	Using the initial dataset variable, display observations from restaurant Mcdonalds. 
For this, I filter the restaurant "Mcdonalds" to show only observations related to it-->

```{r}

fastfood %>%
  filter(restaurant=="Mcdonalds")

```

<!--Part 2-->

<!--11.	Display the types of variables in the dataset using skimr package-->

```{r}
library(skimr)

skim(fastfood)

#For this, the skim function will show the type of variables in dataset in the form of summary.

```

<!--12.	Show the count of observations for each restaurant.-->

```{r}
fastfood %>%
count(restaurant, sort=TRUE)

#The count function displays the total observations of each restaurant.

```

<!--13.	Using groupings (group_by()), summarise and display the average number of calories for each restaurant.-->

```{r}

fastfood %>%
  group_by(restaurant) %>%
  summarise(mean_calories = mean(calories))

#For this, first I group the data by restaurant and then use the summarise function to display the mean or average calories of each restaurant.

```

<!--14.	Add a variable to the dataset, which calculates the average calories per type of restaurant and call it average_calories.-->

```{r}

average_calories<-fastfood %>%
  group_by(restaurant) %>%
  mutate(average_calories=mean(calories)) %>%
  ungroup()

#For this, I have first grouped the variable restaurant and then by using the mean function, I have calculated the average calories per restaurant.

```

<!--15.	Display the data viz of total fat per each type of restaurant. Write a narration (2-3 sentences) why you believe this type of data viz presents such information best.-->

```{r}

library(ggplot2)

ggplot(data = fastfood) +
geom_point(mapping = aes(x = restaurant, y = total_fat))

# This data visualization shows very precise comparison of each type of restaurant in comparison to total_fat consumed. We can see that Mcdonalds has the highest number of total_fat of '141' while Dairy Queen has the lowest number of total_fat which is '0' in one of its item. It will give an idea to people that which restaurant can be best if they want lower fat component in their meals. 

```

<!--16.	Add a variable to the dataset, which calculates the maximum total fat per type of restaurant and call it max_total_fat-->

```{r}
max_total_fat<-fastfood %>%
  group_by(restaurant) %>%
  mutate(max_total_fat=max(total_fat)) %>%
  ungroup()

# For calculation of maximum total_fat, we first group it by the restaurant and then use the mutate function to create new variable as well as use max function inside it for delivering values.

```

<!--17.	Use observations for Mcdonalds to plot sugar variable against protein with geom_point()-->

```{r}

ggplot(data = fastfood) +
  geom_point(mapping = aes(x = sugar, y = protein, color = "Mcdonalds"))

```

